name: Build
on:
  workflow_call:
    inputs:
      mode:
        type: string
        required: true
        default: 'staging'
      branch:
        type: string
        required: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch }}
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Run unit tests
        run: npx --no-install vitest run
      - name: Build
        run: npm run build -- --mode=${{ inputs.mode }}
      - name: Upload build directory
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: ./dist
