name: Create release
on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: prod_deploy
  cancel-in-progress: false

jobs:
  build-production:
    uses: ./.github/workflows/build.yml
    with:
      mode: 'production'

  create-release:
    runs-on: ubuntu-latest
    needs: build-production
    steps:
      - uses: actions/checkout@v3
      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token }}
          output-file: 'false'
          tag-prefix: ''
      - name: Create Release
        uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
#  deploy:
#    name: 'Sync to prod S3'
#    runs-on: ubuntu-20.04
#    needs: ['build-production', 'create-release']
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/download-artifact@v2
#        with:
#          name: dist
#          path: ./dist

