name: Run tests

on:
  push:
    branches: ['development']
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: ${{ steps.detect-package-manager.outputs.manager }}
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npx --no-install vitest run
      - name: Build
        run: npm run build
      - name: Save built folders
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: |
            dist

  cypress:
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Download built folders
        uses: actions/download-artifact@v2
        with:
          name: dist
      - name: Cypress run
        uses: cypress-io/github-action@v4
        env:
          CYPRESS_APP_URL: http://localhost:3000
        with:
          browser: chrome
          start: npm run dev
          wait-on: 'http://localhost:3000'
      - name: Updload artifacts
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
