name: Run tests

on:
  push:
    branches: ['development']
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  VITE_SERVER_URL: http://localhost:3001

jobs:
  build-staging:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      mode: 'production'

  cypress:
    runs-on: ubuntu-20.04
    needs: build-staging
    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: ./dist
      - name: Cypress run
        uses: cypress-io/github-action@v4
        env:
          CYPRESS_BASE_URL: http://localhost:3001
        with:
          browser: chrome
          start: npm run preview
          wait-on: 'http://localhost:3001'
      - name: Updload artifacts
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
