name: Run tests

on:
  push:
    branches: ['development']
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  VITE_SERVER_URL: http://localhost:3001

jobs:
  build-staging:
    uses: ./.github/workflows/build.yml
    with:
      mode: 'production'

  cypress:
    runs-on: ubuntu-20.04
    needs: build-staging
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: ./dist
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          start: npm run preview
          wait-on: 'http://localhost:3001'
      - name: Updload artifacts
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
